In [3]:
import numpy as np
import torch

In [233]:
stage = "0"
pickle = True
batch_size2 = np.load("debug"+stage+"_2.npy", allow_pickle=pickle)
batch_size3 = np.load("debug"+stage+"_6.npy", allow_pickle=pickle)

In [234]:
batch_size2.shape

(8,)

In [235]:
batch_size3.shape

(8,)

In [249]:
text_inputs, text_lengths, mels, max_len, output_lengths, *_, speaker_ids = batch_size2
text_inputs2, text_lengths2, mels2, max_len2, output_lengths2, *_2, speaker_ids2 = batch_size3
x = speaker_ids
y = speaker_ids2
print(x[0] == y[0])
print(x[1] == y[3])
print("~~~~~ under should be mostly false ~~~~~"); print(x[1] == y[2])

tensor(True, device='cuda:0')
tensor(True, device='cuda:0')
~~~~~ under should be mostly false ~~~~~
tensor(False, device='cuda:0')


In [232]:
speaker_ids[1]

tensor(199, device='cuda:0')

In [250]:
print(batch_size2)

[tensor([[ 57,  60,  46,  49,  46,  44,  45,  57,  11,  60,  52,  58,  49,  41,
          11,  45,  38,  59,  42,  11,  57,  52,  11,  39,  42,  49,  46,  42,
          59,  42,   6,  11,  57,  45,  38,  57,  11,  56,  45,  42,   3,  56,
          11,  57,  45,  42,  11,  49,  42,  38,  41,  42,  55,  11,  57,  45,
          38,  57,  11,  60,  42,  11,  38,  49,  49,  11,  48,  51,  52,  60,
          11,  56,  45,  42,  11,  46,  56,   7,   9],
        [145, 141,  11, 106,  70, 143,  11,  94, 119, 112,  11,  85,  90, 113,
          73,   6,  11,  88, 109, 105,  11, 118,  70, 116,  10,   9,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0]], device='cuda:0')
 tensor([79, 26], device='cuda:0')
 tensor([[[ -5.1645,  -5.6108,  -5.9575,  ...,

In [251]:
print(batch_size3)

[tensor([[ 57,  60,  46,  49,  46,  44,  45,  57,  11,  60,  52,  58,  49,  41,
          11,  45,  38,  59,  42,  11,  57,  52,  11,  39,  42,  49,  46,  42,
          59,  42,   6,  11,  57,  45,  38,  57,  11,  56,  45,  42,   3,  56,
          11,  57,  45,  42,  11,  49,  42,  38,  41,  42,  55,  11,  57,  45,
          38,  57,  11,  60,  42,  11,  38,  49,  49,  11,  48,  51,  52,  60,
          11,  56,  45,  42,  11,  46,  56,   7,   9],
        [132, 137,  90,  11, 144, 113,  11, 133,  94, 117,  11, 106,  98,  11,
          91,  70, 133,  11, 144, 113, 143,  11, 116, 117, 109, 130,  90,  11,
          82, 133,  11,  82, 130,   6,  11, 106,  73, 118,  11, 118,  74,  91,
          97,  11, 104,  74, 116,  97,   7,   9,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0],
        [ 46,  51,  57,  42,  51,  57,  11,  52,  51,  11,  56,  57,  42,  38,
          49,  46,  

In [186]:
batch_size2[0,:,:]

IndexError: too many indices for array

In [187]:
batch_size3[0,:,:]

IndexError: too many indices for array

In [188]:
print(batch_size2[0,:,:].shape)
print(batch_size3[0,:,:].shape)
correct = 0
total = len(batch_size2[0,:,:].flatten(0))
for i in range(len(batch_size2[0,:,:].flatten(0))):
    if batch_size2[0,:,:].flatten(0)[i] == batch_size3[0,:,:].flatten(0)[i]: correct+=1
print(str((correct/total)*100)+"% identical")

print(batch_size2[0,:,:] == batch_size3[0,:,:]) # should be the same
print(batch_size2[1,:,:] == batch_size3[1,:,:]) # should be the same
print(batch_size2[1,:,:] == batch_size3[2,:,:]) # should be different

IndexError: too many indices for array

In [12]:
t = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [13]:
t.shape

torch.Size([3, 4])

In [14]:
t.squeeze()

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [15]:
t.unsqueeze(0).shape

torch.Size([1, 3, 4])

In [16]:
from layers import TacotronSTFT, STFT
from hparams import create_hparams
hparams = create_hparams()
# allows WaveGlow from Ground Truth
from utils import load_wav_to_torch
stft = TacotronSTFT(hparams.filter_length, hparams.hop_length, hparams.win_length,
                    hparams.n_mel_channels, hparams.sampling_rate, hparams.mel_fmin,
                    hparams.mel_fmax)
def load_mel(path):
    audio, sampling_rate = load_wav_to_torch(path)
    if sampling_rate != stft.sampling_rate:
        raise ValueError("{} {} SR doesn't match target {} SR".format(
            sampling_rate, stft.sampling_rate))
    audio_norm = audio / hparams.max_wav_value
    audio_norm = audio_norm.unsqueeze(0)
    audio_norm = torch.autograd.Variable(audio_norm, requires_grad=False)
    melspec = stft.mel_spectrogram(audio_norm)
    return melspec

/home/cookie/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/cookie/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/cookie/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/cookie/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: 


For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.



In [17]:
x = load_mel("/media/cookie/MoreStable/ClipperDatasetV2/SlicedDialogue/Special source/Outtakes/819 outtakes/00_59_34_Starlight_Annoyed Sarcastic__Do you suppose the terrifying trunk escape is too much for a Pony who drinks all the juice and talks nonstop in her sleep_.wav")

In [18]:
y = x.repeat(32,1,1)

In [19]:
y.shape

torch.Size([32, 80, 556])

In [20]:
y.unsqueeze(1).transpose(2,3).shape

torch.Size([32, 1, 556, 80])

In [23]:
y.view(y.size(0), 1, -1, 80).shape

torch.Size([32, 1, 556, 80])

In [22]:
y.unsqueeze(1).transpose(2,3) == y.view(y.size(0), 1, -1, 80)

tensor([[[[ True, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False,  True]]],


        [[[ True, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False,  True]]],


        [[[ True, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, Fa

In [44]:
list_ = [0,0,0,0,1,0,0,0,0,0]

In [45]:
assert len(list_) == 10 # confirm the list is the correct length (10 in default params)

In [52]:
torch.FloatTensor(list_).unsqueeze(0)

tensor([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [260]:
tensor = torch.FloatTensor([[[0,1,2,3,4,5],[0,1,2,3,4,5],[0,1,2,3,4,5],[0,1,2,3,4,5]],[[6,7,8,9,10,11],[6,7,8,9,10,11],[6,7,8,9,10,11],[6,7,8,9,10,11]]])
print(tensor)
print(tensor.shape)
print(tensor[0,:])
print(tensor[1,:])
# (B, n_mel_channels, mel_length)
# (n_mel_channels, mel_length)
# mel_channels = 4
# Batch = 2
# mel_length = 6

tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.],
         [ 0.,  1.,  2.,  3.,  4.,  5.],
         [ 0.,  1.,  2.,  3.,  4.,  5.],
         [ 0.,  1.,  2.,  3.,  4.,  5.]],

        [[ 6.,  7.,  8.,  9., 10., 11.],
         [ 6.,  7.,  8.,  9., 10., 11.],
         [ 6.,  7.,  8.,  9., 10., 11.],
         [ 6.,  7.,  8.,  9., 10., 11.]]])
torch.Size([2, 4, 6])
tensor([[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]])
tensor([[ 6.,  7.,  8.,  9., 10., 11.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [ 6.,  7.,  8.,  9., 10., 11.]])


In [261]:
 # (B, n_mel_channels, mel_length) -> [N, 1, time_domain, n_mel_channels]
# mel_channels = 4
# Batch = 2
# mel_length = 6
tensor_ = tensor.view(tensor.size(0),-1,4).unsqueeze(1)
print(tensor_)
print(tensor_.shape)
print(tensor_[0,:])

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  0.,  1.],
          [ 2.,  3.,  4.,  5.],
          [ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  0.,  1.],
          [ 2.,  3.,  4.,  5.]]],


        [[[ 6.,  7.,  8.,  9.],
          [10., 11.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [ 6.,  7.,  8.,  9.],
          [10., 11.,  6.,  7.],
          [ 8.,  9., 10., 11.]]]])
torch.Size([2, 1, 6, 4])
tensor([[[0., 1., 2., 3.],
         [4., 5., 0., 1.],
         [2., 3., 4., 5.],
         [0., 1., 2., 3.],
         [4., 5., 0., 1.],
         [2., 3., 4., 5.]]])


In [262]:
# (B, n_mel_channels, mel_length) -> [N, 1, time_domain, n_mel_channels]
# mel_channels = 4
# Batch = 2
# mel_length = 6
tensor_ = tensor.transpose(1,2).unsqueeze(1)
print(tensor_)
print(tensor_.shape)
print(tensor_[0,:])

tensor([[[[ 0.,  0.,  0.,  0.],
          [ 1.,  1.,  1.,  1.],
          [ 2.,  2.,  2.,  2.],
          [ 3.,  3.,  3.,  3.],
          [ 4.,  4.,  4.,  4.],
          [ 5.,  5.,  5.,  5.]]],


        [[[ 6.,  6.,  6.,  6.],
          [ 7.,  7.,  7.,  7.],
          [ 8.,  8.,  8.,  8.],
          [ 9.,  9.,  9.,  9.],
          [10., 10., 10., 10.],
          [11., 11., 11., 11.]]]])
torch.Size([2, 1, 6, 4])
tensor([[[0., 0., 0., 0.],
         [1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.]]])


In [263]:
# (B, n_mel_channels, mel_length) -> [N, n_mel_channels * mel_length]
# mel_channels = 4
# Batch = 2
# mel_length = 6
tensor_ = tensor.view(tensor.size(0),tensor.size(-2)*tensor.size(-1))
print(tensor_)
print(tensor_.shape)
print(tensor_[0,:])

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  0.,  1.,  2.,  3.,  4.,  5.,  0.,  1.,
          2.,  3.,  4.,  5.,  0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.,  6.,  7.,  8.,  9., 10., 11.,  6.,  7.,
          8.,  9., 10., 11.,  6.,  7.,  8.,  9., 10., 11.]])
torch.Size([2, 24])
tensor([0., 1., 2., 3., 4., 5., 0., 1., 2., 3., 4., 5., 0., 1., 2., 3., 4., 5.,
        0., 1., 2., 3., 4., 5.])
